version: "3.1"

services:
  web:
    build:
      context: ../
    container_name: web
    depends_on:
      - db
    env_file:
      - ../.env
    restart: always

  nginx:
    container_name: nginx
    image: jonasal/nginx-certbot
    restart: unless-stopped
    env_file:
      - ../.env
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx:/etc/letsencrypt
      - ./user_conf.d:/etc/nginx/user_conf.d
    depends_on:
      - web

  db:
    container_name: db
    image: mysql
    env_file:
      - ../.env
    ports:
      - 3306:3306
    restart: always
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
  nginx:
